services:
  # 1. База данных
  postgres:
    image: postgres:15-alpine
    container_name: booking_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-booking_db}
      POSTGRES_USER: ${POSTGRES_USER:-booking_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-booking_password}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  # 2. Основной дашборд (Порт 8501)
  stats:
    build:
      context: ./stats_streamlit
    volumes:
      - ./stats_streamlit:/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-booking_db}
      DB_USER: ${POSTGRES_USER:-booking_user}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-booking_password}
      TZ: Asia/Bishkek
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    depends_on:
      - postgres

  # 3. Твой Telegram Бот (Система бронирования)
  bot:
    build:
      context: ./stats_streamlit
    command: python bot.py
    volumes:
      - ./stats_streamlit:/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-booking_db}
      DB_USER: ${POSTGRES_USER:-booking_user}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-booking_password}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TZ: Asia/Bishkek
    depends_on:
      - postgres

volumes:
  db_data: